"""Generic job-script rendering from Jinja2 templates.

App-agnostic core of the ``job generate`` step. Build-info branding is supplied
by the app through :func:`set_build_info_provider` (so generated headers read
``Generated by <app> v<ver>`` without takflow depending on any app).
"""
from __future__ import annotations

import os
import stat
from pathlib import Path
from typing import Callable, Dict, List, Optional, Union, TYPE_CHECKING

from jinja2 import Environment, FileSystemLoader

from takflow.build_info import get_build_info as _generic_build_info
from takflow.build_info import get_build_info_lines as _generic_build_info_lines
from takflow.config import SlurmWorkload
from takflow.jobspec import TaskResource, to_orvix_directives

if TYPE_CHECKING:
    from takflow.config import BaseWorkflowConfig


# --- build-info provider injection -------------------------------------------

_build_info_provider: Optional[Callable[[], Dict[str, str]]] = None


def set_build_info_provider(provider: Callable[[], Dict[str, str]]) -> None:
    """Register an app callback returning the ``{"warning","info"}`` header dict.

    Called by the app (e.g. on ``import mcv_workflow.job``) so rendered headers
    carry the app's branding. When unset, a generic ``takflow`` header is used.
    """
    global _build_info_provider
    _build_info_provider = provider


def _current_build_info_lines() -> Dict[str, str]:
    if _build_info_provider is not None:
        return _build_info_provider()
    return _generic_build_info_lines(_generic_build_info("unknown"), "takflow")


def render_orvix_resource_block(
    job_type: str = "serial",
    queue: Optional[str] = None,
    partition: Optional[str] = None,
    nodes: Optional[Union[int, str]] = None,
    ntasks_per_node: Optional[Union[int, str]] = None,
    time: Optional[str] = None,
    walltime: Optional[str] = None,
    memory: Optional[str] = None,
    output: Optional[str] = None,
    error: Optional[str] = None,
    project: Optional[str] = None,
    wckey: Optional[str] = None,
    application: Optional[str] = None,
    scheduler: str = "slurm",
    requeue: Optional[bool] = None,
) -> str:
    """Render a ``#ORVIX`` directive block from template-friendly kwargs.

    ``partition`` is accepted as a legacy alias for ``queue``; ``walltime`` is a
    legacy alias for ``time``. ``project`` and ``wckey`` are synonyms (``wckey``
    wins if both given).
    """
    resolved_queue = queue or partition
    resolved_time = time or walltime
    resolved_project = wckey or project

    task = TaskResource(
        job_type=job_type,  # type: ignore[arg-type]
        queue=resolved_queue,
        nodes=int(nodes) if nodes is not None else None,
        ntasks_per_node=int(ntasks_per_node) if ntasks_per_node is not None else None,
        time=resolved_time,
        memory=memory,
        requeue=requeue,
    )
    workload = SlurmWorkload(
        wckey=resolved_project or "",
        application=application,
    )
    spec = task.compile(workload)
    spec.scheduler = scheduler
    if output is not None:
        spec.output = output
    if error is not None:
        spec.error = error
    return "\n".join(to_orvix_directives(spec))


# --- rendering ---------------------------------------------------------------

def render_jobs_from_directory(
    config: "BaseWorkflowConfig",
    repo_base: str,
    output_repo_base: str,
    additional_repo_base: Optional[Union[str, List[str]]] = None,
):
    """Render every ``jobs/**/*.j2`` template under ``repo_base`` into the output.

    Parameters
    ----------
    config : BaseWorkflowConfig
        Workflow config used as template data.
    repo_base : str
        Repo root containing the ``jobs`` template directory.
    output_repo_base : str
        Output repo root.
    additional_repo_base : str or list[str], optional
        Extra Jinja2 template search paths (used by oper extensions to override
        base templates).
    """
    jobs_dir = Path(repo_base, "jobs")
    if not jobs_dir.exists():
        raise FileNotFoundError(f"Jobs directory not found: {jobs_dir}")

    template_search_paths = [repo_base]
    if additional_repo_base is not None:
        if isinstance(additional_repo_base, str):
            template_search_paths.append(additional_repo_base)
        elif isinstance(additional_repo_base, list):
            template_search_paths.extend(additional_repo_base)
        elif isinstance(additional_repo_base, Path):
            template_search_paths.append(str(additional_repo_base))
        else:
            raise TypeError(
                f"error type of additional_repo_base, current is {type(additional_repo_base)}"
            )

    def include_raw(script_path: str) -> str:
        script_file = Path(output_repo_base, script_path)
        if not script_file.exists():
            raise FileNotFoundError(
                f"Script file not found: {script_file}. "
                f"Please run 'resource copy' before 'job generate'."
            )
        with open(script_file, "r") as f:
            content = f.read()

        # ecflow 模式下需用 %nopp/%end 包裹原生脚本内容，
        # 避免 ecflow 预处理器解析脚本中的 % 指令。
        # 注意：保留与 mcv 原实现一致的 12 空格空行，确保字节级输出不变。
        if config.workflow_mode == "ecflow":
            _pad = " " * 12
            content = f"%nopp\n{_pad}\n{content}\n{_pad}\n%end\n"
        return content

    def invoke_script(script_path: str) -> str:
        if config.script_invoke_mode == "inline":
            return include_raw(script_path)
        return f"${{OUTPUT_REPO_BASE}}/{script_path}"

    env = Environment(
        loader=FileSystemLoader(template_search_paths),
        lstrip_blocks=True,
    )
    env.globals["include_raw"] = include_raw
    env.globals["invoke_script"] = invoke_script
    env.globals["render_orvix_resource_block"] = render_orvix_resource_block

    if config.workflow_mode == "shell":
        output_file_suffix = "sh"
    elif config.workflow_mode == "ecflow":
        output_file_suffix = "ecf"
    elif config.workflow_mode == "takler":
        output_file_suffix = "sh"
    else:
        output_file_suffix = "sh"

    j2_files = jobs_dir.rglob("*.j2")
    for j2_file in j2_files:
        relative_path = j2_file.relative_to(repo_base)

        if relative_path.stem.endswith(".sh"):
            base_name = relative_path.stem[:-3]
        else:
            base_name = relative_path.stem

        output_file_relative_path = Path(
            relative_path.parent, f"{base_name}.{output_file_suffix}"
        )

        render_single_job_file(
            relative_path=relative_path,
            output_repo_base=output_repo_base,
            output_relative_path=output_file_relative_path,
            config=config,
            env=env,
        )

        print(f"Generated: {output_file_relative_path}")


def render_single_job_file(
    relative_path: Path,
    output_repo_base: str,
    output_relative_path: Path,
    config: "BaseWorkflowConfig",
    env: Environment,
):
    """Render one job template file into the output repo (executable)."""
    base_name = output_relative_path.stem
    output_log_dict = generate_output_log_data(
        config=config,
        name=base_name,
        output_repo_base=output_repo_base,
    )

    build_info_lines = _current_build_info_lines()
    data = {
        "config": config,
        "build_info_warning": build_info_lines["warning"],
        "build_info_detail": build_info_lines["info"],
        **output_log_dict,
    }

    template = env.get_template(relative_path.as_posix())
    rendered_content = template.render(data)

    output_file_path = Path(output_repo_base, output_relative_path)
    output_file_path.parent.mkdir(exist_ok=True, parents=True)

    with open(output_file_path, "w") as f:
        f.write(rendered_content)

    mode = os.stat(output_file_path).st_mode
    os.chmod(output_file_path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def generate_output_log_data(
    config: "BaseWorkflowConfig", name: str, output_repo_base: str
) -> Dict[str, str]:
    """Compute stdout/stderr log path template data for a job by mode/workload."""
    data: Dict[str, str] = {}
    workflow_mode = config.workflow_mode
    workload_type = config.workload.workload_type
    if workload_type == "slurm":
        if workflow_mode == "shell":
            output_std_log_path = Path(output_repo_base, "logs", f"{name}.%j.out")
            output_stderr_log_path = Path(output_repo_base, "logs", f"{name}.%j.err")
            output_std_log_path.parent.mkdir(parents=True, exist_ok=True)
            data["output_std_log_path"] = str(output_std_log_path)
            data["output_stderr_log_path"] = str(output_stderr_log_path)
        elif workflow_mode == "ecflow":
            data["output_std_log_path"] = r"%ECF_JOBOUT%"
            data["output_stderr_log_path"] = r"%ECF_JOBOUT%.err"
        elif workflow_mode == "takler":
            data["output_std_log_path"] = r"{{ TAKLER_JOBOUT }}"
            data["output_stderr_log_path"] = r"{{ TAKLER_JOBOUT }}.err"
    return data


__all__ = [
    "render_jobs_from_directory",
    "render_single_job_file",
    "generate_output_log_data",
    "set_build_info_provider",
]
