"""Generic build-info header generation.

Apps bind a tool name + version; takflow renders the standard
``AUTO-GENERATED`` warning and the ``Generated by <tool> v<ver> at <ts>`` line
injected into every generated file.
"""
from __future__ import annotations

from datetime import datetime, timezone

from pydantic import BaseModel


class BuildInfo(BaseModel):
    """Build metadata.

    Attributes
    ----------
    build_time : datetime
        Build time (UTC).
    version : str
        Version string.
    """

    build_time: datetime
    version: str


def get_build_info(version: str) -> BuildInfo:
    """Return a :class:`BuildInfo` stamped now (UTC) with ``version``."""
    return BuildInfo(build_time=datetime.now(timezone.utc), version=version)


def get_build_info_lines(build_info: BuildInfo, tool_name: str) -> dict[str, str]:
    """Render the standard header lines for ``tool_name``.

    Returns a dict with ``"warning"`` and ``"info"`` keys.
    """
    ts = build_info.build_time.strftime("%Y-%m-%dT%H:%M:%SZ")
    return {
        "warning": "AUTO-GENERATED FILE - DO NOT EDIT. Changes will be overwritten.",
        "info": f"Generated by {tool_name} v{build_info.version} at {ts}",
    }


__all__ = ["BuildInfo", "get_build_info", "get_build_info_lines"]
